name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create ECR repository
        run: |
          aws ecr create-repository --repository-name desafiorep --region us-east-1

      - name: Create Elastic Beanstalk environment
        run: |
          aws elasticbeanstalk create-application --application-name desafio --region us-east-1
          aws elasticbeanstalk create-environment --environment-name desafioname --application-name desafio --solution-stack-name 64bit Amazon Linux 2 v5.4.3 running Node.js 14 --region us-east-1
