name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <AWS_REGION>

      - name: Create ECR repository
        run: |
          aws ecr create-repository --repository-name <REPO_NAME> --region <AWS_REGION>

      - name: Create Elastic Beanstalk environment
        run: |
          aws elasticbeanstalk create-application --application-name <APP_NAME> --region <AWS_REGION>
          aws elasticbeanstalk create-environment --environment-name <ENV_NAME> --application-name <APP_NAME> --solution-stack-name <SOLUTION_STACK> --region <AWS_REGION>
